# Generated by Django 4.2.7 on 2024-01-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoversPackers', '0002_remove_siteuser_professional_remove_siteuser_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='shiftingdate',
            field=models.DateField(null=True),
        ),
    ]
